#!/bin/bash
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Initialize secrets, download sample videos, and generate .env
# for the full-stack (SceneScape + Loss Prevention) deployment.
#
# Usage: ./init.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS_DIR="${SCRIPT_DIR}/scenescape/secrets"
ENV_FILE="${SCRIPT_DIR}/docker/.env"
SAMPLE_DATA_DIR="${SCRIPT_DIR}/scenescape/sample_data"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

echo -e "${GREEN}=== Storewide Loss Prevention - Full Stack Init ===${NC}"
echo ""

# ---- Step 1: Generate SceneScape secrets ----
echo -e "${YELLOW}[1/3] Generating SceneScape secrets...${NC}"
chmod +x "${SECRETS_DIR}/generate_secrets.sh"
bash "${SECRETS_DIR}/generate_secrets.sh"

# ---- Step 2: Download sample videos ----
echo -e "${YELLOW}[2/3] Downloading sample retail videos...${NC}"
mkdir -p "${SAMPLE_DATA_DIR}"

# These are the retail demo videos used by DLStreamer pipeline
# They get loaded into the vol-sample-data volume
VIDEO_BRANCH="main"
VIDEO_URL="https://github.com/open-edge-platform/edge-ai-resources/raw/refs/heads/${VIDEO_BRANCH}/videos"
VIDEOS=("apriltag-cam1.ts" "apriltag-cam2.ts")

NEED_DOWNLOAD=false
for VIDEO in "${VIDEOS[@]}"; do
  if [ ! -f "${SAMPLE_DATA_DIR}/${VIDEO}" ]; then
    NEED_DOWNLOAD=true
    break
  fi
done

if [ "${NEED_DOWNLOAD}" = true ]; then
  echo "Downloading videos from GitHub..."
  for VIDEO in "${VIDEOS[@]}"; do
    if [ ! -f "${SAMPLE_DATA_DIR}/${VIDEO}" ]; then
      echo "  Downloading ${VIDEO}..."
      curl -k -L -s "${VIDEO_URL}/${VIDEO}" -o "${SAMPLE_DATA_DIR}/${VIDEO}" &
    fi
  done
  wait

  for VIDEO in "${VIDEOS[@]}"; do
    if [ ! -f "${SAMPLE_DATA_DIR}/${VIDEO}" ]; then
      echo -e "${RED}ERROR: Failed to download ${VIDEO}${NC}"
      exit 1
    fi
  done
  echo "  Videos downloaded successfully."
else
  echo "  Videos already present, skipping download."
fi

# ---- Step 3: Generate .env file ----
echo -e "${YELLOW}[3/3] Generating docker/.env...${NC}"

# Read generated secrets — honor SUPASS from environment if set
SUPASS="${SUPASS:-$(cat "${SECRETS_DIR}/supass" 2>/dev/null || echo "")}"
DBPASS=$(sed -nr "/DATABASE_PASSWORD=/s/.*'([^']+)'/\1/p" "${SECRETS_DIR}/django/secrets.py" 2>/dev/null || echo "")
CONTROLLER_AUTH=$(cat "${SECRETS_DIR}/controller.auth" 2>/dev/null || echo "")

USER_UID=$(id -u)
USER_GID=$(id -g)

if [ -f "${ENV_FILE}" ]; then
  echo "  ${ENV_FILE} already exists. Backing up to ${ENV_FILE}.bak"
  cp "${ENV_FILE}" "${ENV_FILE}.bak"
fi

cat > "${ENV_FILE}" <<EOF
# Auto-generated by init.sh — $(date -Iseconds)
SECRETSDIR=${SECRETS_DIR}
SUPASS=${SUPASS}
DATABASE_PASSWORD=${DBPASS}
CONTROLLER_AUTH=${CONTROLLER_AUTH}
UID=${USER_UID}
GID=${USER_GID}

# SceneScape image versions
SCENESCAPE_REGISTRY=
SCENESCAPE_VERSION=v2026.0.0
DLSTREAMER_VERSION=2026.1.0-20260331-weekly-ubuntu24

# Store
STORE_NAME=Retail
STORE_ID=store_001

# LP
LP_SERVICE_PORT=8082
LOG_LEVEL=INFO

# SeaweedFS
SEAWEEDFS_S3_PORT=8333
SEAWEEDFS_MASTER_PORT=9333
SEAWEEDFS_VOLUME_PORT=8080

# SceneScape API (for zone auto-discovery)
SCENESCAPE_API_USER=admin
SCENESCAPE_API_PASSWORD=${SUPASS}
EOF

echo ""
echo -e "${GREEN}=== Init complete ===${NC}"
echo ""
echo "Generated files:"
echo "  Secrets:  ${SECRETS_DIR}/"
echo "  Videos:   ${SAMPLE_DATA_DIR}/"
echo "  Env:      ${ENV_FILE}"
echo ""
echo -e "SUPASS: ${YELLOW}${SUPASS}${NC}"
echo ""
echo "Next steps:"
echo "  1. Review docker/.env and adjust proxy/image settings if needed"
echo "  2. Start the full stack:"
echo "       cd ${SCRIPT_DIR}"
echo "       docker compose -f docker/docker-compose.full.yaml up -d"
echo "     or:"
echo "       make demo"
echo ""
echo "  3. Open SceneScape UI:  https://localhost"
echo "     Login: admin / ${SUPASS}"
echo "  4. Open Gradio UI:      http://localhost:7860"
