#!/bin/bash
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Resolve the SceneScape Scene UID dynamically by querying the SceneScape API.
# Authenticates with username/password, fetches the first scene, and writes
# SCENE_UID into the .env file.
#
# Usage: ./scripts/resolve_scene_uid.sh [env-file]
#
# Reads SCENESCAPE_API_URL, SCENESCAPE_API_USER, SCENESCAPE_API_PASSWORD
# from docker/.env (generated by make init).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

ENV_FILE="${1:-${APP_DIR}/.env}"
DOCKER_ENV="${APP_DIR}/docker/.env"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

# ── Load credentials from docker/.env ──
if [ ! -f "${DOCKER_ENV}" ]; then
    echo -e "${YELLOW}WARNING: docker/.env not found — run 'make init' first${NC}"
    exit 0
fi

SCENESCAPE_API_URL=$(grep '^SCENESCAPE_API_URL=' "${ENV_FILE}" 2>/dev/null | cut -d= -f2- || echo "")
SCENESCAPE_API_USER=$(grep '^SCENESCAPE_API_USER=' "${DOCKER_ENV}" 2>/dev/null | cut -d= -f2- || echo "admin")
SCENESCAPE_API_PASSWORD=$(grep '^SCENESCAPE_API_PASSWORD=' "${DOCKER_ENV}" 2>/dev/null | cut -d= -f2- || echo "")

if [ -z "${SCENESCAPE_API_URL}" ]; then
    echo -e "${YELLOW}WARNING: SCENESCAPE_API_URL not set in ${ENV_FILE} — skipping scene UID resolution${NC}"
    exit 0
fi

if [ -z "${SCENESCAPE_API_PASSWORD}" ]; then
    echo -e "${YELLOW}WARNING: SCENESCAPE_API_PASSWORD not set in ${DOCKER_ENV} — skipping scene UID resolution${NC}"
    exit 0
fi

# ── Check if SCENE_UID is already set ──
CURRENT_UID=$(grep '^SCENE_UID=' "${ENV_FILE}" 2>/dev/null | cut -d= -f2-)
if [ -n "${CURRENT_UID}" ]; then
    echo -e "  SCENE_UID already set: ${GREEN}${CURRENT_UID}${NC}"
    exit 0
fi

echo "  Resolving SCENE_UID from SceneScape API..."

# ── Wait for SceneScape API to be ready (up to 60s) ──
MAX_WAIT=60
WAITED=0
while [ ${WAITED} -lt ${MAX_WAIT} ]; do
    HTTP_CODE=$(curl -sk -o /dev/null -w '%{http_code}' \
        -X POST "${SCENESCAPE_API_URL}/api/v1/auth" \
        -H "Content-Type: application/json" \
        -d "{\"username\":\"${SCENESCAPE_API_USER}\",\"password\":\"${SCENESCAPE_API_PASSWORD}\"}" \
        2>/dev/null || echo "000")

    if [ "${HTTP_CODE}" = "200" ]; then
        break
    fi
    sleep 2
    WAITED=$((WAITED + 2))
    echo "  Waiting for SceneScape API... (${WAITED}s)"
done

if [ "${HTTP_CODE}" != "200" ]; then
    echo -e "${YELLOW}WARNING: SceneScape API not reachable at ${SCENESCAPE_API_URL} (HTTP ${HTTP_CODE})${NC}"
    echo "  SCENE_UID will remain empty. Set it manually in ${ENV_FILE}"
    exit 0
fi

# ── Authenticate ──
AUTH_RESPONSE=$(curl -sk -X POST "${SCENESCAPE_API_URL}/api/v1/auth" \
    -H "Content-Type: application/json" \
    -d "{\"username\":\"${SCENESCAPE_API_USER}\",\"password\":\"${SCENESCAPE_API_PASSWORD}\"}" \
    2>/dev/null)

TOKEN=$(echo "${AUTH_RESPONSE}" | python3 -c "import sys,json; print(json.load(sys.stdin).get('token',''))" 2>/dev/null)

if [ -z "${TOKEN}" ]; then
    echo -e "${YELLOW}WARNING: Failed to authenticate with SceneScape API${NC}"
    exit 0
fi

# ── Fetch scenes ──
SCENES_RESPONSE=$(curl -sk "${SCENESCAPE_API_URL}/api/v1/scenes" \
    -H "Authorization: Token ${TOKEN}" \
    2>/dev/null)

SCENE_UID=$(echo "${SCENES_RESPONSE}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
scenes = data if isinstance(data, list) else data.get('results', data.get('scenes', []))
if scenes:
    print(scenes[0].get('uid', ''))
" 2>/dev/null)

if [ -z "${SCENE_UID}" ]; then
    echo -e "${YELLOW}WARNING: No scenes found in SceneScape${NC}"
    exit 0
fi

# ── Write SCENE_UID to .env ──
if grep -q '^SCENE_UID=' "${ENV_FILE}"; then
    sed -i "s|^SCENE_UID=.*|SCENE_UID=${SCENE_UID}|" "${ENV_FILE}"
else
    echo "SCENE_UID=${SCENE_UID}" >> "${ENV_FILE}"
fi

SCENE_COUNT=$(echo "${SCENES_RESPONSE}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
scenes = data if isinstance(data, list) else data.get('results', data.get('scenes', []))
print(len(scenes))
" 2>/dev/null)

echo -e "  SCENE_UID resolved: ${GREEN}${SCENE_UID}${NC}"
if [ "${SCENE_COUNT}" -gt 1 ] 2>/dev/null; then
    echo -e "  ${YELLOW}NOTE: ${SCENE_COUNT} scenes found — using the first one.${NC}"
    echo "  To use a different scene, set SCENE_UID manually in ${ENV_FILE}"
fi
